ExpertSystemsProject/Models/ExpertSystem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using ExpertSystemsProject.Resources;

namespace ExpertSystemsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertSystem
    {
        public ExpertSystem()
        {
            this.Parameter = new HashSet<Parameter>();
        }

        [Display(Name = "Id", ResourceType = typeof(Resources.Resources))]
        public int idExpertSystem { get; set; }

        [Required]
        [Display(Name = "ExpertSystem_Name", ResourceType = typeof(Resources.Resources))]
        public string Name { get; set; }

        [Display(Name = "ExpertSystem_Description", ResourceType = typeof(Resources.Resources))]
        public string Description { get; set; }
    
        public virtual ICollection<Parameter> Parameter { get; set; }
    }
}

ExpertSystemsProject/Controllers/DBControllers/ExpertSystemsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ExpertSystemsProject.Models;

namespace ExpertSystemsProject.Controllers.DBControllers
{
    public class ExpertSystemsController : BaseController, IDbController
    {
        private readonly ExpertSystemDBEntities _db = new ExpertSystemDBEntities();

        // GET: /ExpertSystems/
        public ActionResult Index()
        {
            List<ExpertSystem> expertSystemsList;
            try
            {
                expertSystemsList = _db.ExpertSystem.ToList();
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
            }

            return View(expertSystemsList);
        }

        // GET: /ExpertSystems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ExpertSystem expertsystem;
            try
            {
                expertsystem = _db.ExpertSystem.Find(id);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
            }

            if (expertsystem == null)
            {
                return HttpNotFound();
            }
            return View(expertsystem);
        }

        // GET: /ExpertSystems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /ExpertSystems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="idExpertSystem,Name,Description")] ExpertSystem expertsystem)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _db.ExpertSystem.Add(expertsystem);
                    _db.SaveChanges();
                }
                catch (Exception)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
                }
                return RedirectToAction("Index");
            }

            return View(expertsystem);
        }

        // GET: /ExpertSystems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ExpertSystem expertsystem;
            try
            {
                expertsystem = _db.ExpertSystem.Find(id);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
            }

            if (expertsystem == null)
            {
                return HttpNotFound();
            }
            return View(expertsystem);
        }

        // POST: /ExpertSystems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="idExpertSystem,Name,Description")] ExpertSystem expertsystem)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _db.Entry(expertsystem).State = EntityState.Modified;
                    _db.SaveChanges();
                }
                catch (Exception)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
                }
                return RedirectToAction("Index");
            }
            return View(expertsystem);
        }

        // GET: /ExpertSystems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ExpertSystem expertsystem;
            try
            {
                expertsystem = _db.ExpertSystem.Find(id);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
            }

            if (expertsystem == null)
            {
                return HttpNotFound();
            }
            return View(expertsystem);
        }

        // POST: /ExpertSystems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                ExpertSystem expertsystem = _db.ExpertSystem.Find(id);
                _db.ExpertSystem.Remove(expertsystem);
                _db.SaveChanges();

            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExpertSystemsProject/Controllers/ExpertModeController.cs
using System.Web.Mvc;

namespace ExpertSystemsProject.Controllers
{
    public class ExpertModeController : BaseController
    {
        //
        // GET: /DB/
        public ActionResult Index()
        {
            return View();
        }
	}
}

ExpertSystemsProject/Views/ExpertSystems/Create.cshtml
@model ExpertSystemsProject.Models.ExpertSystem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ExpertSystem</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExpertSystemsProject/Views/ExpertSystems/Delete.cshtml
@model ExpertSystemsProject.Models.ExpertSystem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ExpertSystem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ExpertSystemsProject/Views/ExpertSystems/Details.cshtml
@using ExpertSystemsProject.Resources;
@model ExpertSystemsProject.Models.ExpertSystem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ExpertSystem</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(Resources.Edit, "Edit", new { id = Model.idExpertSystem }) |
    @Html.ActionLink(Resources.Back, "Index")
</p>

ExpertSystemsProject/Views/ExpertSystems/Edit.cshtml
@model ExpertSystemsProject.Models.ExpertSystem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ExpertSystem</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.idExpertSystem)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExpertSystemsProject/Views/ExpertSystems/Index.cshtml
@using ExpertSystemsProject.Resources;
@model IEnumerable<ExpertSystemsProject.Models.ExpertSystem>

@{
    ViewBag.Title = Resources.ExpertSystems_Title;
}

<h2>@Resources.ExpertSystems_Title</h2>

<p>
    @Html.ActionLink(Resources.CreateNew, "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idExpertSystem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.idExpertSystem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink(Resources.Edit, "Edit", new { id=item.idExpertSystem }) |
            @Html.ActionLink(Resources.Details, "Details", new { id = item.idExpertSystem }) |
            @Html.ActionLink(Resources.Delete, "Delete", new { id = item.idExpertSystem })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink(Resources.Back, "Index", "ExpertMode")
</div>