ExpertSystemsProject/Controllers/UserModeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ExpertSystemsProject.Models;
using ExpertSystemsProject.Models.Enums;


namespace ExpertSystemsProject.Controllers
{
    public class UserModeController : BaseController
    {
        private readonly ExpertSystemDBEntities _db = new ExpertSystemDBEntities();
        private const string SessionExpertiseModelName = "ExpertiseModel";

        private ExpertiseModel ExpertiseModel
        {
            get
            {
                if (System.Web.HttpContext.Current.Session[SessionExpertiseModelName] == null)
                {
                    System.Web.HttpContext.Current.Session.Add(SessionExpertiseModelName, new ExpertiseModel());
                }
                return System.Web.HttpContext.Current.Session[SessionExpertiseModelName] as ExpertiseModel;
            }
            set
            {
                if (System.Web.HttpContext.Current.Session[SessionExpertiseModelName] == null)
                {
                    System.Web.HttpContext.Current.Session.Add(SessionExpertiseModelName, value);
                }
                else
                {
                    System.Web.HttpContext.Current.Session[SessionExpertiseModelName] = value;
                }
            }
        }

        private readonly Expertise _expertise;

        public UserModeController()
        {
            _expertise = new Expertise(ExpertiseModel);
        }

        //
        // GET: /UserMode/
        public ActionResult SelectExpertSystem(int? id)
        {
            if (id != null)
            {
                ViewBag.SelectedExpertSystemID = id.Value;
            }

            List<ExpertSystem> expertSystemsList;
            try
            {
                expertSystemsList = _db.ExpertSystem.ToList();
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
            }

            return View(expertSystemsList);
        }

        //
        // GET: /UserMode/SelectTargetParameter
        public ActionResult SelectTargetParameter(int? expertSystemId, int? parameterId)
        {
            List<Parameter> parametersList;
            try
            {
                if (expertSystemId != null)
                {
                    //Заносим выбранную базу данных.
                    ExpertiseModel.ExpertSystem = _db.ExpertSystem.Find(expertSystemId);
                }

                if (parameterId != null)
                {
                    //Передаем виду Id выделенного элемента(для отрисовки).
                    ViewBag.SelectedParameterID = parameterId;
                }

                if ((expertSystemId == null) && (ExpertiseModel.ExpertSystem == null))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }


                //Загружаем данные из бд.
                var parameters = _db.Parameter.Include(p => p.ExpertSystem).Include(p => p.ParameterRelationType)
                    .Include(p => p.ParameterType);

                if (parameters == null)
                {
                    return HttpNotFound();
                }

                //Получаем не истоковые параметры заданной экспертной системы.
                parameters = parameters.Where(parameter1 => parameter1.ExpertSystem_idExpertSystem
                    == ExpertiseModel.ExpertSystem.idExpertSystem)
                    .Where(parameter1 => parameter1.ParameterRelationType_idRelationType != 1);

                try
                {
                    parametersList = parameters.ToList();
                }
                catch (Exception)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
                }
            }
            catch (EntityException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
            }

            return View(parametersList);
        }

        //
        // GET: /UserMode/SelectTargetParameter
        public ActionResult FillSourceParameters(int? parameterId)
        {
            try
            {
                //Проверяем выбрана ли экспертная система(для запросов к БД)
                if (ExpertiseModel.ExpertSystem == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                //Проверяем выбран ли целевой параметр и Id параметра (для запросов к БД)
                if ((ExpertiseModel.TargetParameters == null) && (parameterId == null))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                try
                {
                    //Загружаем данные из бд.
                    var targetParameters = _db.Parameter.Include(p => p.ExpertSystem).Include(p => p.ParameterRelationType)
                        .Include(p => p.ParameterType);

                    if (targetParameters == null)
                    {
                        return HttpNotFound();
                    }
                    var targetParameter = _db.Parameter.Find(parameterId);
                    //Получаем не истоковые параметры заданной экспертной системы.
                    targetParameters = targetParameters.Where(parameter1 => parameter1.ExpertSystem_idExpertSystem
                        == ExpertiseModel.ExpertSystem.idExpertSystem)
                        .Where(parameter1 => parameter1.Name == targetParameter.Name);

                    ExpertiseModel.TargetParameters = targetParameters.ToList();
                    ExpertiseModel.OutputPaths = _expertise.GetAllOutputPaths(ExpertiseModel.TargetParameters);
                    ExpertiseModel.OutputPaths = _expertise.RemoveParametersDublicates(ExpertiseModel.OutputPaths);
                }
                catch (Exception)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
                }

                if (ExpertiseModel.OutputPaths == null)
                {
                    return HttpNotFound();
                }

                ViewBag.ParametersValuesDictionary = _expertise.GetParametersValuesDictionaries();
            }
            catch (EntityException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
            }

            return View();
        }

        // POST: /Parameters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FillSourceParameters(List<List<int>> selectedParametersValuesIdList)
        {
            try
            {
                if (selectedParametersValuesIdList == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                }

                ExpertiseModel.SelectedParametersValues = new List<Dictionary<Parameter, ParameterValue>>();

                var parametersValuesDictionaryList = _expertise.GetParametersValuesDictionaries();

                for (int j = 0; j < parametersValuesDictionaryList.Length; j++)
                {
                    ExpertiseModel.SelectedParametersValues.Add(new Dictionary<Parameter, ParameterValue>());
                    int i = 0;
                    foreach (var dictionary in parametersValuesDictionaryList[j])
                    {
                        if (dictionary.Key.ParameterRelationType.RelationType ==
                            Enum.GetName(typeof(ParameterRelationTypeEnum), ParameterRelationTypeEnum.Source))
                        {
                            foreach (var parameterValue in dictionary.Value)
                            {
                                if (parameterValue.idParameterValue == selectedParametersValuesIdList[j][i])
                                {
                                    ExpertiseModel.SelectedParametersValues[j]
                                        .Add(dictionary.Key, parameterValue);
                                    break;
                                }
                            }
                            i++;
                        }
                    }
                }

                return RedirectToAction("Result");
                
            }
            catch (EntityException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
            }
        }

        //
        // GET: /UserMode/SelectTargetParameter
        public ActionResult Result()
        {
            var resultList = new Dictionary<string,List<string>>();
            ExpertiseModel.Result = new List<ParameterValue>();
            var clauses = _db.Clause.ToList();

            try
            {
                if (ExpertiseModel.Result == null)
                    ExpertiseModel.Result = new List<ParameterValue>();


                for (int i = 0; i < ExpertiseModel.OutputPaths.Count; i++)
                {
                    //Упорядочиваем путь вывода
                    ExpertiseModel.OutputPaths[i].Reverse();

                    ExpertiseModel.Result.Add(_expertise.GetResult(i));
                    Clause resultClause;
                    if (ExpertiseModel.Result[i].Parameter.ParameterRelationType_idRelationType != 3)

ExpertSystemsProject/Views/UserMode/FillSourceParameters.cshtml
@using ExpertSystemsProject.Models;
@using ExpertSystemsProject.Models.Enums
@using ExpertSystemsProject.Resources;
@model List<List<int>>

@{
    ViewBag.Title = Resources.FillSourceParameters_Title;
}

<h2>@Resources.FillSourceParameters_Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    var parametersValuesDictionary = (Dictionary<Parameter, List<ParameterValue>>[])ViewBag.ParametersValuesDictionary;

    for (int j = 0; j < parametersValuesDictionary.Length; j++)
    {
        <hr/>
        int i = 0;
        

        foreach (var item in parametersValuesDictionary[j])
        {
            var parameter = item.Key;
            if (parameter.ParameterRelationType.RelationType != 
                Enum.GetName(typeof (ParameterRelationTypeEnum), ParameterRelationTypeEnum.Source))
            {
                continue; 
            }
            var selectList = new SelectList(item.Value, "idParameterValue", "Value");
        
            <div class="form-horizontal">
                <h4>Parameter</h4>

                <div class="form-group">
                    @Html.Label(Resources.Parameter_Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.Label(parameter.Name);
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label(Resources.Value, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model[j][i], selectList)
                    </div>
                </div>
            </div>
            <hr />
            i++;
        }
    }
    
    <div class="btn-group">
        @Html.ActionLink(Resources.Back, "SelectTargetParameter", "UserMode", new { @class = "btn btn-default btn-left" })
        <input type="submit" value=@Resources.NextStep class="btn btn-primary btn-right" />
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExpertSystemsProject/Views/UserMode/Result.cshtml
@using ExpertSystemsProject.Resources

@model Dictionary<string, List<string>>

@{
    ViewBag.Title = @Resources.Result;
    int counter = 0;
}

<h2>@Resources.Result</h2>
@foreach (var key in Model.Keys)
{
    counter++;
    <hr/>
    <br />
    @Html.Label(String.Format(@Resources.Result + " {0}:", counter), new { @class = "h3" });
    <br />
    @Html.Label(key, new { @class = "h3" });
    <br />
    <br />

    @Html.Label(@Resources.Explanation, new { @class = "h4" });

    
    foreach (var explanation in Model[key])
    {
        <br />
        @Html.Label(explanation);
    }
    <hr/>
}

ExpertSystemsProject/Views/UserMode/SelectExpertSystem.cshtml
@using ExpertSystemsProject.Resources

@model IEnumerable<ExpertSystemsProject.Models.ExpertSystem>

@{
    ViewBag.Title = Resources.SelectExpertSystem_Title;
}

<h2>@Resources.SelectExpertSystem_Title</h2>

<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
    </tr>
    @foreach (var item in Model) 
    {
        string classNameOfSelectedRow = "";
    
        <!--Если id совпадает с с выбранным, выделяем строку-->
        if (item.idExpertSystem == ViewBag.SelectedExpertSystemID)
        {
            classNameOfSelectedRow = "success";
        }
    
        <tr class="@classNameOfSelectedRow">
            <td>

                @Html.ActionLink(Resources.Select, "SelectExpertSystem", new { id = item.idExpertSystem })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        </tr>
    }

</table>

<div class="btn-group">
    @if (ViewBag.SelectedExpertSystemID != null)
    {
        @Html.ActionLink(Resources.NextStep, "SelectTargetParameter", new { expertSystemId = ViewBag.SelectedExpertSystemID }, new { @class = "btn btn-primary btn-right" })
    }
</div>

ExpertSystemsProject/Views/UserMode/SelectTargetParameter.cshtml
@using ExpertSystemsProject.Resources

@model IEnumerable<ExpertSystemsProject.Models.Parameter>

@{
    ViewBag.Title = Resources.SelectTargetParameter_Title;
    bool isSameParameter = false;
    string parameterName = null;
}

<h2>@Resources.SelectTargetParameter_Title</h2>

<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InfluencingParameters)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ParameterRelationType.RelationType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ParameterType.Type)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        if ((isSameParameter)&&(parameterName == item.Name))
        {
            continue;
        }
        foreach (var parameter in Model)
        {
            if ((parameter.Name == item.Name) && (parameter.idParameter!=item.idParameter))
            {
                isSameParameter = true;
                parameterName = item.Name;
                break;
            }
        }
        
        string classNameOfSelectedRow = "";

        <!--Если id совпадает с с выбранным, выделяем строку-->
        if (item.idParameter == ViewBag.SelectedParameterID)
        {
            classNameOfSelectedRow = "success";
        }

        <tr class="@classNameOfSelectedRow">
            <td>
                @Html.ActionLink(Resources.Select, "SelectTargetParameter", new { parameterId = item.idParameter })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InfluencingParameters)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParameterRelationType.RelationType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParameterType.Type)
            </td>
        </tr>
    }

</table>
<div class="btn-group">
    @Html.ActionLink(Resources.Back, "SelectExpertSystem", "UserMode", new { @class = "btn btn-default btn-left" })
    @if (ViewBag.SelectedParameterID != null)
    {
        @Html.ActionLink(Resources.NextStep, "FillSourceParameters", new { parameterId = ViewBag.SelectedParameterID}, new { @class = "btn btn-primary btn-right" })
    }
</div>